### ISSUE TITLE
Remove the FireContext JsonCredentials

### ISSUE THREAD

**Issue by jeremylcarter** [sn0wfl4k3s/Firenet#4]
Hi,

Thanks for your library. With the `FireContext` I was wondering if we could remove the `JsonCredentials` string because you should not be using that, you should be using the environment variable `GOOGLE_APPLICATION_CREDENTIALS`. Perhaps there is a need for the `JsonCredentials` string path but that would only be for testing.

Do you mind if I raise a PR to suggest an alternative way of configuring?

**Comment by sn0wfl4k3s** [comment]
Hello,

Thanks for your help, with the PR. The main reason for jsoncredentials, was because i wanted maybe build a distributed persistance in future with more than one firestore database configured but i'm not sure about that. But you're right, it needs that also (enviroment variable). i'll see your PR, thanks.

Oh pls, i'll appreciate an alternative way of configuring.

**Comment by sn0wfl4k3s** [comment]
Hi, 
I removed the JsonCredentials and now by default it is getting from the GOOGLE_APPLICATION_CREDENTIALS environment variable in this latest version (1.1.0). I put the news in the readme too. Any other problem is just talk.

Thanks again for the ideia, i'll close here.
